FROM python:3.8-slim

WORKDIR /app

# Install system-level dependencies needed for h5py & zoneinfo builds
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libhdf5-dev \
    pkg-config \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Rust and Cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"

COPY . /app

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/bash"]
