FROM python:3.8-slim

WORKDIR /app

# Install system-level dependencies needed for h5py & zoneinfo builds
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libhdf5-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/bash"]
