artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://docs.google.com/spreadsheets/d/1mW6Agx4ueXhuM6D9yrUlt2uc_C1nHN5o/edit?usp=sharing
  local_data_file: artifacts/data_ingestion/lapse-rate.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["lapse-rate.xlsx"]

data_transformation:
  original_data: artifacts/data_ingestion/lapse-rate.csv
  root_dir: artifacts/transformed_data
  transformed_data_path: artifacts/transformed_data/lapsed_data_encoded.csv
  trainData: artifacts/transformed_data/trainining_data
  testData: artifacts/transformed_data/testing_data
  training_independent_data: artifacts/transformed_data/trainining_data/X_train.csv
  training_dependent_data: artifacts/transformed_data/trainining_data/y_train.csv
  testing_independent_data: artifacts/transformed_data/testing_data/X_test.csv
  testing_dependent_data: artifacts/transformed_data/testing_data/y_test.csv