artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/11LLcJ7ZPn_kRdQ2amBlzBLznV0EdtOfq/view?usp=sharing
  local_data_file: artifacts/data_ingestion/Kaggle (1).csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["Kaggle (1).csv"]

data_transformation:
  original_data: artifacts/data_ingestion/Kaggle (1).csv
  root_dir: artifacts/transformed_data
  transformed_data_path: artifacts/transformed_data/lapsed_data_encoded.csv
  trainData: artifacts/transformed_data/trainining_data
  testData: artifacts/transformed_data/testing_data
  training_independent_data: artifacts/transformed_data/trainining_data/X_train.csv
  training_dependent_data: artifacts/transformed_data/trainining_data/y_train.csv
  testing_independent_data: artifacts/transformed_data/testing_data/X_test.csv
  testing_dependent_data: artifacts/transformed_data/testing_data/y_test.csv