name: Deploy Python Package

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install required dependencies from requirements.txt

      # Run tests (optional)
      - name: Run tests
        run: |
          pytest  # Run tests if you have them set up (modify if using another test framework)

      # Build the distribution files (sdist, wheel)
      - name: Build distribution files
        run: |
          python setup.py sdist bdist_wheel

      # Upload distribution to PyPI (or another destination like AWS S3, custom server, etc.)
      # Upload .whl file as artifact
      - name: Upload .whl file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/*.whl  # Path to the .whl file in the dist folder